/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountView
 */
export interface AccountView {
    /**
     * 
     * @type {number}
     * @memberof AccountView
     */
    accountId?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountView
     */
    accountLoginId?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountView
     */
    accountName?: string;
}

/**
 * Check if a given object implements the AccountView interface.
 */
export function instanceOfAccountView(value: object): value is AccountView {
    return true;
}

export function AccountViewFromJSON(json: any): AccountView {
    return AccountViewFromJSONTyped(json, false);
}

export function AccountViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountView {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'accountLoginId': json['accountLoginId'] == null ? undefined : json['accountLoginId'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
    };
}

export function AccountViewToJSON(value?: AccountView | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'accountLoginId': value['accountLoginId'],
        'accountName': value['accountName'],
    };
}

