/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 카테고리 정보를 담고 있는 DTO
 * @export
 * @interface CategoryInfoRequestDTO
 */
export interface CategoryInfoRequestDTO {
    /**
     * 카테고리 이름
     * @type {string}
     * @memberof CategoryInfoRequestDTO
     */
    categoryName: string;
}

/**
 * Check if a given object implements the CategoryInfoRequestDTO interface.
 */
export function instanceOfCategoryInfoRequestDTO(value: object): value is CategoryInfoRequestDTO {
    if (!('categoryName' in value) || value['categoryName'] === undefined) return false;
    return true;
}

export function CategoryInfoRequestDTOFromJSON(json: any): CategoryInfoRequestDTO {
    return CategoryInfoRequestDTOFromJSONTyped(json, false);
}

export function CategoryInfoRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryInfoRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryName': json['categoryName'],
    };
}

export function CategoryInfoRequestDTOToJSON(value?: CategoryInfoRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'categoryName': value['categoryName'],
    };
}

