/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MenuInfoRequestDTO } from './MenuInfoRequestDTO';
import {
    MenuInfoRequestDTOFromJSON,
    MenuInfoRequestDTOFromJSONTyped,
    MenuInfoRequestDTOToJSON,
} from './MenuInfoRequestDTO';

/**
 * 
 * @export
 * @interface CreateMenuInfoRequest
 */
export interface CreateMenuInfoRequest {
    /**
     * 
     * @type {MenuInfoRequestDTO}
     * @memberof CreateMenuInfoRequest
     */
    menuInfoRequestDTO: MenuInfoRequestDTO;
    /**
     * 
     * @type {Blob}
     * @memberof CreateMenuInfoRequest
     */
    image?: Blob;
}

/**
 * Check if a given object implements the CreateMenuInfoRequest interface.
 */
export function instanceOfCreateMenuInfoRequest(value: object): value is CreateMenuInfoRequest {
    if (!('menuInfoRequestDTO' in value) || value['menuInfoRequestDTO'] === undefined) return false;
    return true;
}

export function CreateMenuInfoRequestFromJSON(json: any): CreateMenuInfoRequest {
    return CreateMenuInfoRequestFromJSONTyped(json, false);
}

export function CreateMenuInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMenuInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'menuInfoRequestDTO': MenuInfoRequestDTOFromJSON(json['menuInfoRequestDTO']),
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function CreateMenuInfoRequestToJSON(value?: CreateMenuInfoRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'menuInfoRequestDTO': MenuInfoRequestDTOToJSON(value['menuInfoRequestDTO']),
        'image': value['image'],
    };
}

