/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 메뉴 추가 옵션 요청에 대한 DTO
 * @export
 * @interface ExtraInfoRequestDTO
 */
export interface ExtraInfoRequestDTO {
    /**
     * 메뉴 추가 옵션명
     * @type {string}
     * @memberof ExtraInfoRequestDTO
     */
    extraName: string;
    /**
     * 메뉴 추가 옵션 가격
     * @type {number}
     * @memberof ExtraInfoRequestDTO
     */
    extraPrice?: number;
}

/**
 * Check if a given object implements the ExtraInfoRequestDTO interface.
 */
export function instanceOfExtraInfoRequestDTO(value: object): value is ExtraInfoRequestDTO {
    if (!('extraName' in value) || value['extraName'] === undefined) return false;
    return true;
}

export function ExtraInfoRequestDTOFromJSON(json: any): ExtraInfoRequestDTO {
    return ExtraInfoRequestDTOFromJSONTyped(json, false);
}

export function ExtraInfoRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtraInfoRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'extraName': json['extraName'],
        'extraPrice': json['extraPrice'] == null ? undefined : json['extraPrice'],
    };
}

export function ExtraInfoRequestDTOToJSON(value?: ExtraInfoRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'extraName': value['extraName'],
        'extraPrice': value['extraPrice'],
    };
}

