/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtraInfoResponseDTO
 */
export interface ExtraInfoResponseDTO {
    /**
     * 생성 시간 정보
     * @type {Date}
     * @memberof ExtraInfoResponseDTO
     */
    createdAt?: Date;
    /**
     * 마지막 수정 시간 정보
     * @type {Date}
     * @memberof ExtraInfoResponseDTO
     */
    updatedAt?: Date;
    /**
     * 삭제 시간 정보
     * @type {Date}
     * @memberof ExtraInfoResponseDTO
     */
    deletedAt?: Date;
    /**
     * 메뉴 추가 옵션 ID값
     * @type {number}
     * @memberof ExtraInfoResponseDTO
     */
    extraId?: number;
    /**
     * 메뉴 추가 옵션명
     * @type {string}
     * @memberof ExtraInfoResponseDTO
     */
    extraName?: string;
    /**
     * 메뉴 추가 옵션 가격
     * @type {number}
     * @memberof ExtraInfoResponseDTO
     */
    extraPrice?: number;
}

/**
 * Check if a given object implements the ExtraInfoResponseDTO interface.
 */
export function instanceOfExtraInfoResponseDTO(value: object): value is ExtraInfoResponseDTO {
    return true;
}

export function ExtraInfoResponseDTOFromJSON(json: any): ExtraInfoResponseDTO {
    return ExtraInfoResponseDTOFromJSONTyped(json, false);
}

export function ExtraInfoResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtraInfoResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'extraId': json['extraId'] == null ? undefined : json['extraId'],
        'extraName': json['extraName'] == null ? undefined : json['extraName'],
        'extraPrice': json['extraPrice'] == null ? undefined : json['extraPrice'],
    };
}

export function ExtraInfoResponseDTOToJSON(value?: ExtraInfoResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'extraId': value['extraId'],
        'extraName': value['extraName'],
        'extraPrice': value['extraPrice'],
    };
}

