/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 로그인 ID 변경 요청 DTO
 * @export
 * @interface LoginIdUpdateDto
 */
export interface LoginIdUpdateDto {
    /**
     * 로그인 ID
     * @type {string}
     * @memberof LoginIdUpdateDto
     */
    loginId: string;
}

/**
 * Check if a given object implements the LoginIdUpdateDto interface.
 */
export function instanceOfLoginIdUpdateDto(value: object): value is LoginIdUpdateDto {
    if (!('loginId' in value) || value['loginId'] === undefined) return false;
    return true;
}

export function LoginIdUpdateDtoFromJSON(json: any): LoginIdUpdateDto {
    return LoginIdUpdateDtoFromJSONTyped(json, false);
}

export function LoginIdUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginIdUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'loginId': json['loginId'],
    };
}

export function LoginIdUpdateDtoToJSON(value?: LoginIdUpdateDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'loginId': value['loginId'],
    };
}

