/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryDtoOnly } from './CategoryDtoOnly';
import {
    CategoryDtoOnlyFromJSON,
    CategoryDtoOnlyFromJSONTyped,
    CategoryDtoOnlyToJSON,
} from './CategoryDtoOnly';

/**
 * 메뉴 및 카테고리 정보
 * @export
 * @interface MenuDtoAndCategoryDto
 */
export interface MenuDtoAndCategoryDto {
    /**
     * 생성 시간 정보
     * @type {Date}
     * @memberof MenuDtoAndCategoryDto
     */
    createdAt?: Date;
    /**
     * 마지막 수정 시간 정보
     * @type {Date}
     * @memberof MenuDtoAndCategoryDto
     */
    updatedAt?: Date;
    /**
     * 삭제 시간 정보
     * @type {Date}
     * @memberof MenuDtoAndCategoryDto
     */
    deletedAt?: Date;
    /**
     * 메뉴 ID값
     * @type {number}
     * @memberof MenuDtoAndCategoryDto
     */
    menuId?: number;
    /**
     * 메뉴 이름
     * @type {string}
     * @memberof MenuDtoAndCategoryDto
     */
    menuName?: string;
    /**
     * 메뉴 가격
     * @type {number}
     * @memberof MenuDtoAndCategoryDto
     */
    menuPrice?: number;
    /**
     * 메뉴 설명
     * @type {string}
     * @memberof MenuDtoAndCategoryDto
     */
    menuSummary?: string;
    /**
     * 메뉴 대표 이미지 url
     * @type {string}
     * @memberof MenuDtoAndCategoryDto
     */
    menuImgUrl?: string;
    /**
     * 
     * @type {CategoryDtoOnly}
     * @memberof MenuDtoAndCategoryDto
     */
    categoryDtoOnly?: CategoryDtoOnly;
}

/**
 * Check if a given object implements the MenuDtoAndCategoryDto interface.
 */
export function instanceOfMenuDtoAndCategoryDto(value: object): value is MenuDtoAndCategoryDto {
    return true;
}

export function MenuDtoAndCategoryDtoFromJSON(json: any): MenuDtoAndCategoryDto {
    return MenuDtoAndCategoryDtoFromJSONTyped(json, false);
}

export function MenuDtoAndCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuDtoAndCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'menuId': json['menuId'] == null ? undefined : json['menuId'],
        'menuName': json['menuName'] == null ? undefined : json['menuName'],
        'menuPrice': json['menuPrice'] == null ? undefined : json['menuPrice'],
        'menuSummary': json['menuSummary'] == null ? undefined : json['menuSummary'],
        'menuImgUrl': json['menuImgUrl'] == null ? undefined : json['menuImgUrl'],
        'categoryDtoOnly': json['categoryDtoOnly'] == null ? undefined : CategoryDtoOnlyFromJSON(json['categoryDtoOnly']),
    };
}

export function MenuDtoAndCategoryDtoToJSON(value?: MenuDtoAndCategoryDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'menuId': value['menuId'],
        'menuName': value['menuName'],
        'menuPrice': value['menuPrice'],
        'menuSummary': value['menuSummary'],
        'menuImgUrl': value['menuImgUrl'],
        'categoryDtoOnly': CategoryDtoOnlyToJSON(value['categoryDtoOnly']),
    };
}

