/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 사용자 이름 변경 요청 DTO
 * @export
 * @interface NameUpdateDto
 */
export interface NameUpdateDto {
    /**
     * 사용자 이름
     * @type {string}
     * @memberof NameUpdateDto
     */
    name: string;
}

/**
 * Check if a given object implements the NameUpdateDto interface.
 */
export function instanceOfNameUpdateDto(value: object): value is NameUpdateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NameUpdateDtoFromJSON(json: any): NameUpdateDto {
    return NameUpdateDtoFromJSONTyped(json, false);
}

export function NameUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameUpdateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NameUpdateDtoToJSON(value?: NameUpdateDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

