/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrdersMenuDtoAndMenuDtoAndCategoryDto } from './OrdersMenuDtoAndMenuDtoAndCategoryDto';
import {
    OrdersMenuDtoAndMenuDtoAndCategoryDtoFromJSON,
    OrdersMenuDtoAndMenuDtoAndCategoryDtoFromJSONTyped,
    OrdersMenuDtoAndMenuDtoAndCategoryDtoToJSON,
} from './OrdersMenuDtoAndMenuDtoAndCategoryDto';

/**
 * 주문 정보 DTO
 * @export
 * @interface OrderInfoResponseDTO
 */
export interface OrderInfoResponseDTO {
    /**
     * 생성 시간 정보
     * @type {Date}
     * @memberof OrderInfoResponseDTO
     */
    createdAt?: Date;
    /**
     * 마지막 수정 시간 정보
     * @type {Date}
     * @memberof OrderInfoResponseDTO
     */
    updatedAt?: Date;
    /**
     * 삭제 시간 정보
     * @type {Date}
     * @memberof OrderInfoResponseDTO
     */
    deletedAt?: Date;
    /**
     * 주문 ID
     * @type {number}
     * @memberof OrderInfoResponseDTO
     */
    orderId?: number;
    /**
     * 
     * @type {Array<OrdersMenuDtoAndMenuDtoAndCategoryDto>}
     * @memberof OrderInfoResponseDTO
     */
    ordersMenuDtoAndMenuDtoAndCategoryDtoList?: Array<OrdersMenuDtoAndMenuDtoAndCategoryDto>;
}

/**
 * Check if a given object implements the OrderInfoResponseDTO interface.
 */
export function instanceOfOrderInfoResponseDTO(value: object): value is OrderInfoResponseDTO {
    return true;
}

export function OrderInfoResponseDTOFromJSON(json: any): OrderInfoResponseDTO {
    return OrderInfoResponseDTOFromJSONTyped(json, false);
}

export function OrderInfoResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderInfoResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'ordersMenuDtoAndMenuDtoAndCategoryDtoList': json['ordersMenuDtoAndMenuDtoAndCategoryDtoList'] == null ? undefined : ((json['ordersMenuDtoAndMenuDtoAndCategoryDtoList'] as Array<any>).map(OrdersMenuDtoAndMenuDtoAndCategoryDtoFromJSON)),
    };
}

export function OrderInfoResponseDTOToJSON(value?: OrderInfoResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'orderId': value['orderId'],
        'ordersMenuDtoAndMenuDtoAndCategoryDtoList': value['ordersMenuDtoAndMenuDtoAndCategoryDtoList'] == null ? undefined : ((value['ordersMenuDtoAndMenuDtoAndCategoryDtoList'] as Array<any>).map(OrdersMenuDtoAndMenuDtoAndCategoryDtoToJSON)),
    };
}

