/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 주문 요청 정보 DTO
 * @export
 * @interface OrderInfoRequestDTO
 */
export interface OrderInfoRequestDTO {
    /**
     * 메뉴 ID값
     * @type {number}
     * @memberof OrderInfoRequestDTO
     */
    menuId?: number;
    /**
     * 메뉴 수량
     * @type {number}
     * @memberof OrderInfoRequestDTO
     */
    amount?: number;
}

/**
 * Check if a given object implements the OrderInfoRequestDTO interface.
 */
export function instanceOfOrderInfoRequestDTO(value: object): value is OrderInfoRequestDTO {
    return true;
}

export function OrderInfoRequestDTOFromJSON(json: any): OrderInfoRequestDTO {
    return OrderInfoRequestDTOFromJSONTyped(json, false);
}

export function OrderInfoRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderInfoRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'menuId': json['menuId'] == null ? undefined : json['menuId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function OrderInfoRequestDTOToJSON(value?: OrderInfoRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'menuId': value['menuId'],
        'amount': value['amount'],
    };
}

