/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 주문 요리 시작 및 완료 시작 처리 정보 DTO
 * @export
 * @interface OrderTimeResponseDTO
 */
export interface OrderTimeResponseDTO {
    /**
     * 생성 시간 정보
     * @type {Date}
     * @memberof OrderTimeResponseDTO
     */
    createdAt?: Date;
    /**
     * 마지막 수정 시간 정보
     * @type {Date}
     * @memberof OrderTimeResponseDTO
     */
    updatedAt?: Date;
    /**
     * 삭제 시간 정보
     * @type {Date}
     * @memberof OrderTimeResponseDTO
     */
    deletedAt?: Date;
    /**
     * 주문 ID값
     * @type {number}
     * @memberof OrderTimeResponseDTO
     */
    orderId?: number;
    /**
     * 주문 시작 시간
     * @type {Date}
     * @memberof OrderTimeResponseDTO
     */
    cookingStartedAt?: Date;
    /**
     * 주문 완료 시간
     * @type {Date}
     * @memberof OrderTimeResponseDTO
     */
    orderFinishedAt?: Date;
}

/**
 * Check if a given object implements the OrderTimeResponseDTO interface.
 */
export function instanceOfOrderTimeResponseDTO(value: object): value is OrderTimeResponseDTO {
    return true;
}

export function OrderTimeResponseDTOFromJSON(json: any): OrderTimeResponseDTO {
    return OrderTimeResponseDTOFromJSONTyped(json, false);
}

export function OrderTimeResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderTimeResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'cookingStartedAt': json['cookingStartedAt'] == null ? undefined : (new Date(json['cookingStartedAt'])),
        'orderFinishedAt': json['orderFinishedAt'] == null ? undefined : (new Date(json['orderFinishedAt'])),
    };
}

export function OrderTimeResponseDTOToJSON(value?: OrderTimeResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'orderId': value['orderId'],
        'cookingStartedAt': value['cookingStartedAt'] == null ? undefined : ((value['cookingStartedAt']).toISOString()),
        'orderFinishedAt': value['orderFinishedAt'] == null ? undefined : ((value['orderFinishedAt']).toISOString()),
    };
}

