/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { CategoryInfoResponseDTO } from './CategoryInfoResponseDTO';
import {
    CategoryInfoResponseDTOFromJSON,
    CategoryInfoResponseDTOFromJSONTyped,
    CategoryInfoResponseDTOToJSON,
} from './CategoryInfoResponseDTO';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageCategoryInfoResponseDTO
 */
export interface PageCategoryInfoResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof PageCategoryInfoResponseDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageCategoryInfoResponseDTO
     */
    totalElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageCategoryInfoResponseDTO
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageCategoryInfoResponseDTO
     */
    last?: boolean;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageCategoryInfoResponseDTO
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PageCategoryInfoResponseDTO
     */
    numberOfElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageCategoryInfoResponseDTO
     */
    size?: number;
    /**
     * 
     * @type {Array<CategoryInfoResponseDTO>}
     * @memberof PageCategoryInfoResponseDTO
     */
    content?: Array<CategoryInfoResponseDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageCategoryInfoResponseDTO
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageCategoryInfoResponseDTO
     */
    sort?: SortObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageCategoryInfoResponseDTO
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageCategoryInfoResponseDTO interface.
 */
export function instanceOfPageCategoryInfoResponseDTO(value: object): value is PageCategoryInfoResponseDTO {
    return true;
}

export function PageCategoryInfoResponseDTOFromJSON(json: any): PageCategoryInfoResponseDTO {
    return PageCategoryInfoResponseDTOFromJSONTyped(json, false);
}

export function PageCategoryInfoResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageCategoryInfoResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(CategoryInfoResponseDTOFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageCategoryInfoResponseDTOToJSON(value?: PageCategoryInfoResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'first': value['first'],
        'last': value['last'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'numberOfElements': value['numberOfElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(CategoryInfoResponseDTOToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'empty': value['empty'],
    };
}

