/* tslint:disable */
/* eslint-disable */
/**
 * Kkokio API
 * <h3>JWT 토큰 구조</h3> <ul>     <li>subject: accountId</li>     <li>issuedAt: 발급 시간</li>     <li>expiration: 만료 시간</li>     <li>claims:</li>     <ol>         <li>username: 보여지는 이름</li>         <li>roles: 권한들</li>     </ol> </ul> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreInfoRequestDTO
 */
export interface StoreInfoRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof StoreInfoRequestDTO
     */
    storeName: string;
    /**
     * 
     * @type {string}
     * @memberof StoreInfoRequestDTO
     */
    storeAddress: string;
    /**
     * 
     * @type {string}
     * @memberof StoreInfoRequestDTO
     */
    storeSummary: string;
}

/**
 * Check if a given object implements the StoreInfoRequestDTO interface.
 */
export function instanceOfStoreInfoRequestDTO(value: object): value is StoreInfoRequestDTO {
    if (!('storeName' in value) || value['storeName'] === undefined) return false;
    if (!('storeAddress' in value) || value['storeAddress'] === undefined) return false;
    if (!('storeSummary' in value) || value['storeSummary'] === undefined) return false;
    return true;
}

export function StoreInfoRequestDTOFromJSON(json: any): StoreInfoRequestDTO {
    return StoreInfoRequestDTOFromJSONTyped(json, false);
}

export function StoreInfoRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreInfoRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'storeName': json['storeName'],
        'storeAddress': json['storeAddress'],
        'storeSummary': json['storeSummary'],
    };
}

export function StoreInfoRequestDTOToJSON(value?: StoreInfoRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'storeName': value['storeName'],
        'storeAddress': value['storeAddress'],
        'storeSummary': value['storeSummary'],
    };
}

